feat: haoN logo
keycap-archivist/website pull request #491
Opened 2024-09-22 22:52 UTC by ankitsxchdeva

title

2024-09-23 02:34 UTC, anhthang commented
@ankitsxchdeva Image should be in 500x500 and have some padding to have better view when display in the website

2024-09-23 02:35 UTC, anhthang requested changes
@ankitsxchdeva Image should be in 500x500 and have some padding to have better view when display in the website

2024-09-24 23:13 UTC, ankitsxchdeva commented
updated, please let me know if this one works! @anhthang

2024-09-25 04:27 UTC, anhthang approved these changes

2024-09-25 04:27 UTC, merged